language: node_js
node_js:
  - '14.12.0'
os: osx
cache: yarn
jobs:
  include:
    - stage: Test
      name: Unit tests and linting
      script:
        - yarn eslint '{src,example}/**/*.{js,ts,tsx}'
        - yarn test
    - stage: Build
      name: Build
      script:
        - yarn build
    - stage: Docs
      name: Build docs
      script:
        - yarn build:docs
      if: tag IS present
deploy:
  - provider: npm
    skip_cleanup: true
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    keep_history: true
    github_token: $GITHUB_TOKEN
    local_dir: docs
    on:
      tags: true
      condition: -d docs
