language: node_js
node_js:
  - '14.12.0'
os: osx
cache: yarn
jobs:
  include:
    - stage: Test
      name: Unit tests and linting
      script:
        - yarn eslint '{src,example}/**/*.{js,ts,tsx}'
        - yarn test
    - stage: Build
      script:
        - yarn build
    - stage: Release
      script: echo "Deploying to NPM..."
      if: tag IS present
      deploy:
        - provider: npm
          api_key: $NPM_API_TOKEN
          email: $NPM_EMAIL
          skip_cleanup: true
          on:
            tags: true
    - stage: Docs
      name: Build docs
      script:
        - yarn build:docs
      if: tag IS present
      deploy:
        - provider: pages
          skip_cleanup: true
          keep_history: true
          github_token: $GITHUB_TOKEN
          local_dir: docs
          on:
            tags: true
            condition: -d docs
