language: node_js
node_js:
  - '14.12.0'
os: osx
cache: yarn
jobs:
  include:
    - stage: Test
      name: Unit tests and linting
      script:
        - yarn eslint '{src,example}/**/*.{js,ts,tsx}'
        - yarn test
deploy:
  provider: npm
  on:
    tags: true
